# Compiler & flags
CXX       := g++
CPPFLAGS  := -Iinclude -Isrc
CXXFLAGS  := -MMD -MP -Wall -g
LDLIBS    := -lncurses -lsqlite3

# Targets & sources
TARGET    := main
SRC_DIR   := src
INC_DIR   := include

# Find all .cpp files under src/ (one level deep; add more globs if needed)
SOURCES   := $(wildcard $(SRC_DIR)/*.cpp) $(wildcard $(SRC_DIR)/*/*.cpp) $(wildcard $(SRC_DIR)/*/*/*.cpp)
OBJS      := $(SOURCES:.cpp=.o)
DEPS      := $(OBJS:.o=.d)


# Allow overriding (e.g., make BEAR=compiledb compile_commands.json)
BEAR ?= bear

# Files that, if changed, should trigger a re-gen of compile_commands.json
COMPILE_DB_DEPS := $(SOURCES) $(wildcard $(INC_DIR)/**/*.hpp) Makefile

.PHONY: all clean
all: $(TARGET)

.PHONY: compile_commands.json
compile_commands.json: $(COMPILE_DB_DEPS)
	@echo "Rebuilding compile_commands.json with $(BEAR)…"
	# Force a rebuild so $(BEAR) can record all compile commands
	$(BEAR) -- make -B -j

.PHONY: clean-compile-db
clean-compile-db:
	rm -f compile_commands.json

$(TARGET): $(OBJS)
	$(CXX) $(CXXFLAGS) $(OBJS) -o $@ $(LDLIBS)

# Compile rule (dependency files generated by -MMD -MP)
%.o: %.cpp
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) -c $< -o $@

# Include auto-generated dependency files
-include $(DEPS)

clean:
	rm -f $(TARGET) $(OBJS) $(DEPS)

