# Compiler & flags
CXX       := g++
CPPFLAGS  := -Iinclude -Isrc
CXXFLAGS  := -MMD -MP -Wall -g
LDLIBS    := -lncurses -lsqlite3

# Targets & sources
TARGET    := main
SRC_DIR   := src
INC_DIR   := include

# Find all .cpp files under src/ (one level deep; add more globs if needed)
SOURCES   := $(wildcard $(SRC_DIR)/*.cpp) $(wildcard $(SRC_DIR)/*/*.cpp) $(wildcard $(SRC_DIR)/*/*/*.cpp)
OBJS      := $(SOURCES:.cpp=.o)
DEPS      := $(OBJS:.o=.d)

.PHONY: all clean
all: $(TARGET)

$(TARGET): $(OBJS)
	$(CXX) $(CXXFLAGS) $(OBJS) -o $@ $(LDLIBS)

# Compile rule (dependency files generated by -MMD -MP)
%.o: %.cpp
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) -c $< -o $@

# Include auto-generated dependency files
-include $(DEPS)

clean:
	rm -f $(TARGET) $(OBJS) $(DEPS)

